function getLorem() {
    return `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor enim vel justo pharetra vulputate. Nunc imperdiet, lacus ut interdum feugiat, odio turpis tempor sapien, sed facilisis tortor justo in tellus. Nulla consequat arcu ut lobortis pellentesque. Maecenas dictum, nunc id dictum feugiat, odio sapien congue ante, at blandit arcu metus non mi. Cras eu ullamcorper justo. Proin eget massa eget diam venenatis consectetur. Nam massa orci, blandit sed laoreet et, hendrerit non sapien. Nullam quis odio non diam mollis condimentum id ut eros. Quisque augue felis, fringilla eget laoreet eu, feugiat at nulla. Quisque molestie tortor eget nisi bibendum, nec feugiat ligula porta.

Morbi rutrum blandit odio, in tincidunt augue lacinia eget. Cras id congue enim, eget volutpat eros. Aliquam erat volutpat. Cras gravida quis eros at pulvinar. Suspendisse nec tempor ex. Morbi a nisl est. Praesent bibendum elit in elit gravida imperdiet. Fusce vitae luctus purus. Duis egestas sapien nec urna congue volutpat. Vestibulum ac lacus ultricies dui auctor ornare ac sed enim.

Suspendisse potenti. Vivamus diam odio, consequat ac odio at, consequat porta enim. Suspendisse sit amet eros viverra, tincidunt felis id, aliquet lorem. Maecenas id nunc ipsum. Fusce laoreet aliquam felis a hendrerit. Proin et eros sed libero dapibus condimentum. Fusce maximus erat tincidunt augue placerat consequat. Nam vitae volutpat est. Suspendisse ut augue tellus. Sed non justo ac velit vehicula imperdiet. Quisque at maximus velit. Vestibulum in maximus erat. Vivamus ut leo nulla. Vestibulum pulvinar ligula ac nisl aliquam posuere. Maecenas vitae fermentum nulla. Vestibulum aliquam nisi vel sem hendrerit pellentesque.

Fusce id sapien quis quam volutpat accumsan at vitae felis. Curabitur ut hendrerit turpis, et consectetur nisi. Donec mattis nisi leo. Ut tortor massa, euismod eu ipsum sed, finibus condimentum nunc. Donec sit amet ligula libero. Ut id suscipit ligula. Cras tincidunt consectetur nibh, sed iaculis ligula molestie sed. Sed fermentum sem ac purus interdum, eu scelerisque purus placerat. Mauris eget ullamcorper quam. Curabitur ligula purus, tempus ac molestie mollis, mollis hendrerit felis.

Pellentesque vulputate placerat dolor, vestibulum posuere nunc vestibulum eu. Sed dignissim nisi eu risus fringilla, nec consectetur purus pulvinar. Proin elementum est arcu, sit amet maximus quam ultricies ut. Sed molestie nisl feugiat, venenatis augue eget, imperdiet nisi. Integer odio libero, sollicitudin id neque id, volutpat dignissim purus. Duis nec cursus lacus, non sodales nisi. Ut vel nunc eu mauris tempor tempor a sit amet sapien. Aliquam fringilla vehicula eros, ac accumsan turpis semper eu. Mauris suscipit imperdiet erat nec dignissim. Integer id tempus nisi. Praesent urna leo, efficitur vitae tempor sit amet, pellentesque ut dui. Phasellus sit amet diam dui. `;
}

